### ISSUE TITLE
Cannot generate new filter.

### ISSUE THREAD

**Issue by Chadmodan** [flapanther33781/poe-filter#6]
I have the program downloaded and extracted. I can open the .py file and I get the GUI. I can interact with the GUI use the slkiders etc, but when I hit generate filter I get an error. 

Traceback (most recent call last):
  File "C:\Users\Chad\Desktop\New folder\scripts\010-main.py", line 7, in <module>
    task1 = __import__('015-ninja')
  File "C:\Users\Chad\Desktop\New folder\scripts\015-ninja.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by flapanther33781** [comment]
Thanks for checking it out.  Don't just download `00-super-simple-loot-filter.py`, download the whole repository as a zip.  The script you're running is just the GUI front end that then calls the scripts in the scripts folder, which will be installed in the correct place when you unzip the zip file.

I arranged everything this way to simplify things for users, as most people will just use the GUI and then the filters it spits out, which will be placed in the top level folder along with `00-super-simple-loot-filter.py`.  In fact, when you download the zip it'll include the most recent filters I generated and placed on here.  You can delete those, then you'll see the one you create get saved there.  Otherwise it may just overwrite one of these, unless you pick some other settings (since the filename is based on the settings chosen).

I'll leave this open for now. Let me know if you have any other questions or get it working.

**Comment by Chadmodan** [comment]
I have the whole Zip dl'd I see the scripts file with the scripts in it. I'm running htem out of the folder after it's been unzipped to a folder on my deskptop.

**Comment by Chadmodan** [comment]
![image](https://user-images.githubusercontent.com/88566672/133022922-1795b407-9339-4bad-a78a-f89a667d0e7b.png)

**Comment by flapanther33781** [comment]
Hmm.  I thought the `requests` library was part of the default Python library but maybe not.  You might need install the `requests` library to run the program.  If you don't mind doing so, the command should be `pip install requests`.  You should be able to do it from any normal command line.  do you know how to get to a command line in Windows?

**Comment by Chadmodan** [comment]
That solved it for me. Thanks for the help.

**Comment by flapanther33781** [comment]
Sure thing!
